import { z } from "zod";

/**
 * Schema for search queries generated by the planner
 */
export const SearchQuerySchema = z.object({
  query: z.string().min(1, "Query must not be empty"),
  intent: z.string().describe("The purpose of this query in the research process"),
  expectedResults: z.array(z.string()).describe("Types of results expected from this query")
});

/**
 * Schema for report sections generated by the planner
 */
export const ReportSectionSchema = z.object({
  name: z.string().min(1, "Section name must not be empty"),
  description: z.string().min(1, "Section description must not be empty"),
  research: z.boolean(),
  content: z.string().optional(),
  keyPoints: z.array(z.string()).optional(),
  estimatedLength: z.number().int().positive().optional()
});

/**
 * Schema for the complete report plan
 */
export const ReportPlanSchema = z.object({
  topic: z.string(),
  sections: z.array(ReportSectionSchema),
  searchQueries: z.array(SearchQuerySchema),
  estimatedResearchTime: z.number().int().positive(),
  suggestedApproach: z.string()
});

/**
 * Schema for section content generation
 */
export const SectionContentSchema = z.object({
  title: z.string(),
  content: z.string().min(150).max(200),
  keyFindings: z.array(z.string()).min(1),
  citations: z.array(z.object({
    text: z.string(),
    url: z.string().url(),
    relevance: z.number().min(0).max(1)
  })),
  structuralElement: z.discriminatedUnion("type", [
    z.object({
      type: z.literal("table"),
      headers: z.array(z.string()),
      rows: z.array(z.array(z.string()))
    }),
    z.object({
      type: z.literal("list"),
      items: z.array(z.string()).min(3).max(5)
    }),
    z.object({
      type: z.literal("none")
    })
  ])
});

/**
 * Schema for section grading results
 */
export const SectionGradeSchema = z.object({
  grade: z.enum(["pass", "fail"]),
  score: z.number().min(0).max(100),
  feedback: z.array(z.object({
    aspect: z.string(),
    comment: z.string(),
    suggestion: z.string().optional()
  })),
  followUpQueries: z.array(SearchQuerySchema).optional()
});

/**
 * Schema for final sections (intro/conclusion)
 */
export const FinalSectionSchema = z.object({
  type: z.enum(["introduction", "conclusion"]),
  title: z.string(),
  content: z.string().min(50).max(150),
  structuralElement: z.discriminatedUnion("type", [
    z.object({
      type: z.literal("table"),
      headers: z.array(z.string()),
      rows: z.array(z.array(z.string()))
    }),
    z.object({
      type: z.literal("none")
    })
  ]),
  keyTakeaways: z.array(z.string()).optional(),
  reasoningChain: z.array(z.string()).optional()
});

export type SearchQuery = z.infer<typeof SearchQuerySchema>;
export type ReportSection = z.infer<typeof ReportSectionSchema>;
export type ReportPlan = z.infer<typeof ReportPlanSchema>;
export type SectionContent = z.infer<typeof SectionContentSchema>;
export type SectionGrade = z.infer<typeof SectionGradeSchema>;
export type FinalSection = z.infer<typeof FinalSectionSchema>; 