/**
 * Standard error code format: DOMAIN_ACTION_ISSUE
 * 
 * Examples:
 * - AUTH_LOGIN_FAILED
 * - DOCUMENT_UPLOAD_INVALID
 * - CHAT_MESSAGE_NOT_FOUND
 */

// Auth domain error codes
export const AUTH_ERROR_CODES = {
  LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  SIGNUP_FAILED: 'AUTH_SIGNUP_FAILED',
  PASSWORD_RESET_FAILED: 'AUTH_PASSWORD_RESET_FAILED',
  EMAIL_VERIFICATION_FAILED: 'AUTH_EMAIL_VERIFICATION_FAILED',
  MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
  MFA_INVALID: 'AUTH_MFA_INVALID',
  ACCESS_DENIED: 'AUTH_ACCESS_DENIED'
}

// Document domain error codes
export const DOCUMENT_ERROR_CODES = {
  UPLOAD_FAILED: 'DOCUMENT_UPLOAD_FAILED',
  PROCESSING_ERROR: 'DOCUMENT_PROCESSING_ERROR',
  NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  SIZE_TOO_LARGE: 'DOCUMENT_SIZE_TOO_LARGE',
  INVALID_FORMAT: 'DOCUMENT_INVALID_FORMAT',
  EXTRACTION_FAILED: 'DOCUMENT_EXTRACTION_FAILED',
  STORAGE_ERROR: 'DOCUMENT_STORAGE_ERROR',
  PERMISSION_DENIED: 'DOCUMENT_PERMISSION_DENIED',
  DELETE_FAILED: 'DOCUMENT_DELETE_FAILED',
  UPDATE_FAILED: 'DOCUMENT_UPDATE_FAILED'
}

// Chat domain error codes
export const CHAT_ERROR_CODES = {
  CREATION_FAILED: 'CHAT_CREATION_FAILED',
  NOT_FOUND: 'CHAT_NOT_FOUND',
  MESSAGE_FAILED: 'CHAT_MESSAGE_FAILED',
  MESSAGE_NOT_FOUND: 'CHAT_MESSAGE_NOT_FOUND',
  ATTACHMENT_FAILED: 'CHAT_ATTACHMENT_FAILED',
  DELETE_FAILED: 'CHAT_DELETE_FAILED',
  UPDATE_FAILED: 'CHAT_UPDATE_FAILED',
  PERMISSION_DENIED: 'CHAT_PERMISSION_DENIED',
  RATE_LIMIT_EXCEEDED: 'CHAT_RATE_LIMIT_EXCEEDED',
  CONTEXT_OVERFLOW: 'CHAT_CONTEXT_OVERFLOW'
}

// AI/LLM domain error codes
export const AI_ERROR_CODES = {
  GENERATION_FAILED: 'AI_GENERATION_FAILED',
  MODERATION_FAILED: 'AI_MODERATION_FAILED',
  CONTENT_FLAGGED: 'AI_CONTENT_FLAGGED',
  EMBEDDING_FAILED: 'AI_EMBEDDING_FAILED',
  API_ERROR: 'AI_API_ERROR',
  RATE_LIMIT_EXCEEDED: 'AI_RATE_LIMIT_EXCEEDED',
  MODEL_NOT_AVAILABLE: 'AI_MODEL_NOT_AVAILABLE',
  REQUEST_TIMEOUT: 'AI_REQUEST_TIMEOUT',
  INVALID_PROMPT: 'AI_INVALID_PROMPT'
}

// User domain error codes
export const USER_ERROR_CODES = {
  CREATION_FAILED: 'USER_CREATION_FAILED',
  NOT_FOUND: 'USER_NOT_FOUND',
  UPDATE_FAILED: 'USER_UPDATE_FAILED',
  DELETE_FAILED: 'USER_DELETE_FAILED',
  ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INVALID_INPUT: 'USER_INVALID_INPUT',
  PERMISSION_DENIED: 'USER_PERMISSION_DENIED',
  PROFILE_INCOMPLETE: 'USER_PROFILE_INCOMPLETE'
}

// API domain error codes
export const API_ERROR_CODES = {
  VALIDATION_FAILED: 'API_VALIDATION_FAILED',
  RATE_LIMIT_EXCEEDED: 'API_RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'API_INTERNAL_ERROR',
  BAD_REQUEST: 'API_BAD_REQUEST',
  UNAUTHORIZED: 'API_UNAUTHORIZED',
  FORBIDDEN: 'API_FORBIDDEN',
  NOT_FOUND: 'API_NOT_FOUND',
  METHOD_NOT_ALLOWED: 'API_METHOD_NOT_ALLOWED',
  TIMEOUT: 'API_TIMEOUT',
  DATABASE_ERROR: 'API_DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'API_EXTERNAL_SERVICE_ERROR'
}

// Database domain error codes
export const DB_ERROR_CODES = {
  CONNECTION_FAILED: 'DB_CONNECTION_FAILED',
  QUERY_FAILED: 'DB_QUERY_FAILED',
  CONSTRAINT_VIOLATION: 'DB_CONSTRAINT_VIOLATION',
  TRANSACTION_FAILED: 'DB_TRANSACTION_FAILED',
  RECORD_NOT_FOUND: 'DB_RECORD_NOT_FOUND',
  DUPLICATE_RECORD: 'DB_DUPLICATE_RECORD',
  INVALID_SCHEMA: 'DB_INVALID_SCHEMA',
  MIGRATION_FAILED: 'DB_MIGRATION_FAILED'
}

// Storage domain error codes
export const STORAGE_ERROR_CODES = {
  UPLOAD_FAILED: 'STORAGE_UPLOAD_FAILED',
  DOWNLOAD_FAILED: 'STORAGE_DOWNLOAD_FAILED',
  DELETE_FAILED: 'STORAGE_DELETE_FAILED',
  UPDATE_FAILED: 'STORAGE_UPDATE_FAILED',
  NOT_FOUND: 'STORAGE_NOT_FOUND',
  PERMISSION_DENIED: 'STORAGE_PERMISSION_DENIED',
  QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',
  INVALID_PATH: 'STORAGE_INVALID_PATH'
}

// Workflow domain error codes
export const WORKFLOW_ERROR_CODES = {
  CREATION_FAILED: 'WORKFLOW_CREATION_FAILED',
  NOT_FOUND: 'WORKFLOW_NOT_FOUND',
  EXECUTION_FAILED: 'WORKFLOW_EXECUTION_FAILED',
  VALIDATION_FAILED: 'WORKFLOW_VALIDATION_FAILED',
  STEP_FAILED: 'WORKFLOW_STEP_FAILED',
  PERMISSION_DENIED: 'WORKFLOW_PERMISSION_DENIED',
  UPDATE_FAILED: 'WORKFLOW_UPDATE_FAILED',
  DELETE_FAILED: 'WORKFLOW_DELETE_FAILED'
}